#!/bin/bash

CSCOPE_DIR="$PWD/cscope"

echo_usage()
{
    echo "Usage: $0 gen|regen|reset [folder]"
    exit -1
}

gen()
{
    while [ $# -gt 0 ]
    do
        FOLDER="$1"
        shift

        if [ ! -d "$CSCOPE_DIR" ]; then
        mkdir "$CSCOPE_DIR"
        fi

        echo "Finding files on $FOLDER ..."
        find "$FOLDER" -name '*.[ch]' \
        -o -name '*.java' \
        -o -name '*properties' \
        -o -name '*.cpp' \
        -o -name '*.cc' \
        -o -name '*.hpp' \
        -o -name '*.py' \
        -o -name '*.php' >> "$CSCOPE_DIR/cscope.files"

        cscope -b -i "$CSCOPE_DIR/cscope.files"
    done

    export CSCOPE_DB="$PWD/cscope.out"
    echo "Exported CSCOPE_DB to: '$CSCOPE_DB'"
}

reset()
{
    if [ -f "$CSCOPE_DIR/cscope.files" ]; then
        echo "" > "$CSCOPE_DIR/cscope.files"
        echo "Resetted cscope captured files"
    fi
}

if [ $# -lt 1 ]; then
    echo_usage
fi

case $1 in
    "gen")
        shift
        gen $*
        ;;
    "reset")
        reset
        ;;
    "regen")
        reset
        shift
        gen $*
        ;;
    *)
        echo_usage
        ;;
esac
